[colors.primary]
background = '#1d1f21'
foreground = '#c5c8c6'

[colors.normal]
black   = '#1d1f21'
red     = '#cc342b'
green   = '#198844'
yellow  = '#fba922'
blue    = '#3971ed'
magenta = '#a36ac7'
cyan    = '#3971ed'
white   = '#c5c8c6'

[colors.bright]
black   = '#969896'
red     = '#cc342b'
green   = '#198844'
yellow  = '#fba922'
blue    = '#3971ed'
magenta = '#a36ac7'
cyan    = '#3971ed'
white   = '#ffffff'

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Left"
mode = "~AppCursor"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "Right"
mode = "~AppCursor"
mods = "Shift"
