# Colors (High Contrast)

# Default colors
[colors.primary]
background = '#444444'
foreground = '#dddddd'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#aaaaaa'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff0000'
green   = '#00ff00'
yellow  = '#ffff00'
blue    = '#0000ff'
magenta = '#ff00ff'
cyan    = '#00ffff'
white   = '#ffffff'

# Bright colors
[colors.bright]
black   = '#000000'
red     = '#ff0000'
green   = '#00ff00'
yellow  = '#ffff00'
blue    = '#0000ff'
magenta = '#ff00ff'
cyan    = '#00ffff'
white   = '#ffffff'

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Left"
mode = "~AppCursor"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "Right"
mode = "~AppCursor"
mods = "Shift"
