# Colors (One Dark)

# Default colors
[colors.primary]
background = '#1e2127'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Left"
mode = "~AppCursor"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "Right"
mode = "~AppCursor"
mods = "Shift"
